

export const Posts: any = [
    { id: 1, description: 'First snow of the year', iconUrl: 'https://images.pexels.com/photos/434090/pexels-photo-434090.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',                     imageUrl: 'https://images.pexels.com/photos/434090/pexels-photo-434090.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',        username: 'striderlice',        comments: [{username: 'username1', comment: 'comment1' }, {username: 'username1', comment: 'comment1' }], likes: 0},
    { id: 2, description: 'Ready for Halloween', iconUrl: 'https://images.pexels.com/photos/825949/pexels-photo-825949.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',                     imageUrl: 'https://images.pexels.com/photos/825949/pexels-photo-825949.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',           username: 'kingtapir',          comments: [{username: 'username2', comment: 'comment2' }], likes: 0},
    { id: 3, description: '', iconUrl: 'https://images.pexels.com/photos/2737393/pexels-photo-2737393.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',                   imageUrl: 'https://images.pexels.com/photos/2737393/pexels-photo-2737393.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',                            username: 'pennycoyote',        comments: [{username: 'username3', comment: 'comment3' }], likes: 0},
    { id: 4, description: 'Das Hund!', iconUrl: 'https://images.pexels.com/photos/333083/pexels-photo-333083.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',                     imageUrl: 'https://images.pexels.com/photos/333083/pexels-photo-333083.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',                     username: 'hemingwaybuck',      comments: [{username: 'username4', comment: 'comment4' }], likes: 0},
    { id: 5, description: '', iconUrl: 'https://images.pexels.com/photos/92380/pexels-photo-92380.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',                       imageUrl: 'https://images.pexels.com/photos/92380/pexels-photo-92380.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',                                username: 'copernicusllama',    comments: [{username: 'username5', comment: 'comment5' }], likes: 0},
    { id: 6, description: '😍😍😍😍', iconUrl: 'https://images.pexels.com/photos/89781/doberman-dog-animal-world-animal-89781.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',   imageUrl: 'https://images.pexels.com/photos/89781/doberman-dog-animal-world-animal-89781.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',  username: 'maximuscockroach',   comments: [{username: 'username6', comment: 'comment6' }], likes: 0},
    { id: 7, description: 'SQUIRREL!!', iconUrl: 'https://images.pexels.com/photos/1346086/pexels-photo-1346086.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',                   imageUrl: 'https://images.pexels.com/photos/1346086/pexels-photo-1346086.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',                  username: 'tobystork',          comments: [{username: 'username7', comment: 'comment7' }], likes: 0},
    { id: 8, description: 'Test subject 08', iconUrl: 'https://images.pexels.com/photos/97082/weimaraner-puppy-dog-snout-97082.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',                imageUrl: 'https://images.pexels.com/photos/97082/weimaraner-puppy-dog-snout-97082.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',          username: 'happygoshawk',       comments: [{username: 'username8', comment: 'comment8' }], likes: 0},
    { id: 9, description: '', iconUrl: 'https://images.pexels.com/photos/1307630/pexels-photo-1307630.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',                          imageUrl: 'https://images.pexels.com/photos/1307630/pexels-photo-1307630.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',                                   username: 'percyhamster',       comments: [{username: 'username9', comment: 'comment9' }], likes: 0},
    {id: 10, description: 'Grumpy Monday', iconUrl: 'https://images.pexels.com/photos/710927/pexels-photo-710927.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',                     imageUrl: 'https://images.pexels.com/photos/710927/pexels-photo-710927.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',                 username: 'sashamarten',        comments: [{username: 'username10', comment: 'comment10' }], likes: 0}

];


// export function findCourseById(courseId:number) {
//     return COURSES.find(course => course.id === courseId);
// }